version: "3.9"

services:
  mysql:
    build:
      context: ./mysql-image-code
    image: mysql-with-schema
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: database-1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  flask-app:
    build:
      context: .
    image: flask-app-image
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: database-1
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:

