# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: print greeting 
      run: echo "hello we are deploying the app in elastic beanstalk"
    - name: bye bye
      run: mkdir newfolder
    - name: Zipping the files
      run: zip -r deployment-package.zip .
    - name: checking directories 
      run: ls 
    - name: elastic beanstalk deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "bench-assignment"
        environment_name: "BenchAssignment-env"
        region: "us-east-1"
        version_label: v1-${{ github.run_id }}
        bucket_name: "elasticbeanstalk-us-east-1-123456789012"
        bucket_key: "deployment-package.zip"
